name: QuickTest tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3

      - name: Download latest nightly Juvix binary
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: anoma/juvix-nightly-builds
          cache: enable

      - name: run quickcheck example
        run: |
          juvix --version
          make run-quickcheck
